### ISSUE TITLE
Can't run a Tango device on Mac OS X

### ISSUE THREAD

**Issue by tango-tickets-migrator** [tango-controls/cppTango#124]
The very ugly "self ldopen mechanism" used to resolve a class symbol doesn't work on Mac OS X. It seems that ldopening the binary from the binary doesn't work the apple platform. The main consequence is to reduce Mac OS X to a pure client platform (.e. can't run a device on it) ! 

Reported by: nleclercq

Original Ticket: [tango-cs/bugs/404](https://sourceforge.net/p/tango-cs/bugs/404)

**Comment by t-b** [comment]
@nleclercq Please reopen if this is still an issue (and of course provide some more info ;)
