### ISSUE TITLE
libevent-devel package include file may clash with tango's

### ISSUE THREAD

**Issue by tango-tickets-migrator** [tango-controls/cppTango#146]
libevent-devel package, described as:

Asynchronous event notification library (development files)

installs a potentially conflicting 'event.h' file under /usr/include.

This may cause issues when compiling tango code, which in its headers includes &lt;event.h&gt;

This include file is installed there at least as ubuntu, debian and OpenSuse are concerned.

Fixes for people running into the problem:

remove libevent-devel
rename /usr/include/event.h (....)

change include priority when compiling tango code so that /usr/include files are included after /path/to/tango/include include files.

Opening a bug report. In the future renaming tango event.h header file may be taken into account.

Giacomo.

Reported by: jacum

Original Ticket: [tango-cs/bugs/521](https://sourceforge.net/p/tango-cs/bugs/521)

**Comment by t-b** [comment]
The tango source distribution 9.3.3 will install the tango headers in `$prefix/include/tango`.
