### ISSUE TITLE
can't find __i686.get_pc_thunk.bx error

### ISSUE THREAD

**Issue by tango-tickets-migrator** [tango-controls/cppTango#200]
in file : cpp/server/jpeg_mmx/jpeg_dct_mmx.cpp

on some 32bits platform/gcc flavour (by ex ubuntu 14.10 32b)
    call __i686.get_pc_thunk.bx

should be 

```
call __x86.get_pc_thunk.bx
```

best regards

Reported by: rplgm

Original Ticket: [tango-cs/bugs/677](https://sourceforge.net/p/tango-cs/bugs/677)

**Comment by t-b** [comment]
Closing for now as the issue is stale. Please reopen if this is still an issue.
