### ISSUE TITLE
Event errors persisting after server restart

### ISSUE THREAD

**Issue by tango-tickets-migrator** [tango-controls/cppTango#230]
We are experiencing issues with event subscriptions that only seem to manifest when subscribing to (change) events from large numbers of devices (100s) across many servers (10s). When restarting the servers, there is a certain probability that the client's subscriptions for all devices on a given server are somewhat corrupted.

The symtoms are that the "corrupt" subscriptions still appear to receive change events as usual, but they _also_ receive errors like this every 10 seconds or so:

> Error: tango://nb-johfor-0:10000/r3-312u5/wat/fsw-02/state
> Tango error stack
> Severity = ERROR 
> Error reason = API_EventTimeout
> Desc : Event channel is not responding anymore, maybe the server or event system is down
> Origin : EventConsumer::KeepAliveThread()

This is the same error that is correctly reported when the servers are really down, it just never goes away for some devices.

I have reproduced this running locally on my machine, with some 1000 dummy python devices across 20 servers, with polling on the State attribute, and with a minimal client written in C++ that listens to the State attribute for all the devices. After killing the servers and starting them again, but keeping the client running, around 3-4 random servers (and the corresponding 100s of devices) exhibit the above problem.

It is an Ubuntu machine, and I have tested with TANGO 8.1.2 (distribution packages) and 9.2.2 (built from tarball). Both times with ZMQ 4.0.5. We also see it in out CentOS 7 production environment and with PyTango clients.

Some thoughts: It seems like this is related to the ZMQ "keepalive" thread, somehow. Perhaps it's not being informed about the new subscription and therefore keeps reporting the error. Also, the randomness in the behavior suggests some race condition. Also, I'm assuming this is a client issue, I have not really looked into if other kinds of devices make a difference.

Reported by: johfor

Original Ticket: [tango-cs/bugs/787](https://sourceforge.net/p/tango-cs/bugs/787)

**Comment by bourtemb** [comment]
Fixed in Tango 9.2.5
