### ISSUE TITLE
API_AsynReplyNotArrived exception thrown when asyn call response is received in the last 20 ms before the timeout expiration

### ISSUE THREAD

**Issue by tango-tickets-migrator** [tango-controls/cppTango#235]
Hi,

The API_AsynReplyNotArrived exception is wrongly thrown when an asynchronous call with timeout (like command_inout_reply(long id, long call_timeout) response is received in the last 20 ms before the call timeout expiration.

Cheers,
Reynald

Reported by: bourtemb

Original Ticket: [tango-cs/bugs/793](https://sourceforge.net/p/tango-cs/bugs/793)

**Comment by Ingvord** [comment]
Please do not create a separate issue for such simple cases (e.g. fix that requires single commit) - use PR directly. Otherwise we just have duplicate entities.

**Comment by tango-tickets-migrator** [comment]
This issue was automatically migrated from a Sourceforge ticket.
