### ISSUE TITLE
[tango][9.2.2] doen not compile on Debian unstable

### ISSUE THREAD

**Issue by tango-tickets-migrator** [tango-controls/cppTango#237]
Hello, while trying to upload 9.2.2 + patch, I got this FTBFS (fail to build from  source)
I attache the build log in order to check all the verion of the gcc, etc...

Cheers

Fred

libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../.. -I../../../lib/cpp/client -I../../../lib/cpp/log4tango/include -I../../../lib/cpp/log4tango/include -I../../../lib/cpp/server -I/usr/include -Wl,-z,relro -I/usr/include -D_TANGO_LIB -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -std=c++11 -D_REENTRANT -DOMNI_UNLOADABLE_STUBS -c eventsupplier.cpp  -fPIC -DPIC -o .libs/eventsupplier.o
In file included from ./eventsupplier.h:68:0,
                 from eventsupplier.cpp:38:
eventsupplier.cpp: In member function ‘bool Tango::EventSupplier::detect_change(Tango::Attribute&, Tango::EventSupplier::SuppliedEventData&, bool, double&, double&, Tango::DevFailed_, bool&, Tango::DeviceImpl_)’:
./tango_config.h:244:38: error: expected unqualified-id before ‘(’ token
         #define Tango_isnan(A)  std::isnan(A)
                                      ^
eventsupplier.cpp:1589:33: note: in expansion of macro ‘Tango_isnan’
                             if (Tango_isnan((_prev_seq_db)[i]) != 0 && Tango_isnan((_curr_seq_db)[i]) == 0)
                                 ^
./tango_config.h:244:38: error: expected unqualified-id before ‘(’ token
         #define Tango_isnan(A)  std::isnan(A)
                                      ^
eventsupplier.cpp:1589:72: note: in expansion of macro ‘Tango_isnan’
                             if (Tango_isnan((_prev_seq_db)[i]) != 0 && Tango_isnan((_curr_seq_db)[i]) == 0)
                                                                        ^
./tango_config.h:244:38: error: expected unqualified-id before ‘(’ token
         #define Tango_isnan(A)  std::isnan(A)
                                      ^
eventsupplier.cpp:1613:33: note: in expansion of macro ‘Tango_isnan’
                             if (Tango_isnan((_prev_seq_db)[i]) != 0 && Tango_isnan((_curr_seq_db)[i]) == 0)
                                 ^
./tango_config.h:244:38: error: expected unqualified-id before ‘(’ token
         #define Tango_isnan(A)  std::isnan(A)
                                      ^
eventsupplier.cpp:1613:72: note: in expansion of macro ‘Tango_isnan’
                             if (Tango_isnan((_prev_seq_db)[i]) != 0 && Tango_isnan((_curr_seq_db)[i]) == 0)
                                                                        ^
./tango_config.h:244:38: error: expected unqualified-id before ‘(’ token
         #define Tango_isnan(A)  std::isnan(A)
                                      ^
eventsupplier.cpp:1719:33: note: in expansion of macro ‘Tango_isnan’
                             if (Tango_isnan((_prev_seq_fl)[i]) != 0 && Tango_isnan((_curr_seq_fl)[i]) == 0)
                                 ^
./tango_config.h:244:38: error: expected unqualified-id before ‘(’ token
         #define Tango_isnan(A)  std::isnan(A)
                                      ^
eventsupplier.cpp:1719:72: note: in expansion of macro ‘Tango_isnan’
                             if (Tango_isnan((_prev_seq_fl)[i]) != 0 && Tango_isnan((_curr_seq_fl)[i]) == 0)
                                                                        ^
./tango_config.h:244:38: error: expected unqualified-id before ‘(’ token
         #define Tango_isnan(A)  std::isnan(A)
                                      ^
eventsupplier.cpp:1742:33: note: in expansion of macro ‘Tango_isnan’
                             if (Tango_isnan((_prev_seq_fl)[i]) != 0 && Tango_isnan((_curr_seq_fl)[i]) == 0)
                                 ^
./tango_config.h:244:38: error: expected unqualified-id before ‘(’ token
         #define Tango_isnan(A)  std::isnan(A)
                                      ^
eventsupplier.cpp:1742:72: note: in expansion of macro ‘Tango_isnan’
                             if (Tango_isnan((_prev_seq_fl)[i]) != 0 && Tango_isnan((_curr_seq_fl)[i]) == 0)
                                                                        ^
Makefile:741 : la recette pour la cible « eventsupplier.lo » a échouée
make[6]: **\* [eventsupplier.lo] Erreur 1
make[6] : on quitte le répertoire « /home/picca/Debian/tango/tango/lib/cpp/server »
Makefile:777 : la recette pour la cible « all-recursive » a échouée
make[5]: **\* [all-recursive] Erreur 1
make[5] : on quitte le répertoire « /home/picca/Debian/tango/tango/lib/cpp/server »
Makefile:486 : la recette pour la cible « all-recursive » a échouée
make[4]: **\* [all-recursive] Erreur 1
make[4] : on quitte le répertoire « /home/picca/Debian/tango/tango/lib/cpp »
Makefile:433 : la recette pour la cible « all-recursive » a échouée
make[3]: **\* [all-recursive] Erreur 1
make[3] : on quitte le répertoire « /home/picca/Debian/tango/tango/lib »
Makefile:522 : la recette pour la cible « all-recursive » a échouée
make[2]: **\* [all-recursive] Erreur 1
make[2] : on quitte le répertoire « /home/picca/Debian/tango/tango »
Makefile:452 : la recette pour la cible « all » a échouée
make[1]: **\* [all] Erreur 2
make[1] : on quitte le répertoire « /home/picca/Debian/tango/tango »
dh_auto_build: make -j1 returned exit code 2
debian/rules:16 : la recette pour la cible « build » a échouée
make: **\* [build] Erreur 2
dpkg-buildpackage: erreur: debian/rules build a produit une erreur de sortie de type 2
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc -i -I failed
gbp:error: 'debuild -i -I' failed: it exited with 29

Reported by: piccaf

Original Ticket: [tango-cs/bugs/795](https://sourceforge.net/p/tango-cs/bugs/795)

**Comment by bourtemb** [comment]
Fixed in Tango 9.2.5
