### ISSUE TITLE
[c++]  link against libmysqlclient instead of libmysqlclient_r

### ISSUE THREAD

**Issue by tango-tickets-migrator** [tango-controls/cppTango#239]
Hello, I just received a bug report from the ubuntu guyes about tango 8.1.2,in order to compile with mysql 5.7

You can find on this bug report, a patch for 8.1.2. 

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825081

you can inspire yourself from this patch in order to fix tango 9.2

Cheers

Fred

Reported by: piccaf

Original Ticket: [tango-cs/bugs/797](https://sourceforge.net/p/tango-cs/bugs/797)

**Comment by t-b** [comment]
Manual inspection of https://github.com/tango-controls/TangoSourceDistribution/blob/7651ca83d7c6412ead17c9cb8db66e86560d8cce/assets/configure.ac#L292 makes me believe that this is nowadays already fixed. Please reopen if this is not the case.
