### ISSUE TITLE
Memory leak for old compilers

### ISSUE THREAD

**Issue by tango-tickets-migrator** [tango-controls/cppTango#240]
Memory leak in DeviceData classs copy constructor if Tango lib is compiled with an old gcc compiler release 
(< 4.3). For instance, this is the case for Red Hat 4

Fixed in SVN

Reported by: taurel

Original Ticket: [tango-cs/bugs/798](https://sourceforge.net/p/tango-cs/bugs/798)

**Comment by hardion** [comment]
To be closed (sorry for the spam)

**Comment by bourtemb** [comment]
Fixed in Tango 9.2.5
