### ISSUE TITLE
Read value for attribute xxx has not been updated

### ISSUE THREAD

**Issue by tango-tickets-migrator** [tango-controls/cppTango#241]
If you use the read_attributes (Note the s) call to read at the same moment two (or more) attributes with
att2 pushing event for att1, you received the error "read value for attribute att1 has not been updated" when
reading att1

Fixed in SVN

Reported by: taurel

Original Ticket: [tango-cs/bugs/799](https://sourceforge.net/p/tango-cs/bugs/799)

**Comment by hardion** [comment]
To be closed (sorry for the spam)

**Comment by bourtemb** [comment]
Fixed in Tango 9.2.5
