### ISSUE TITLE
Memory leak for R/W spectrum string attribute

### ISSUE THREAD

**Issue by tango-tickets-migrator** [tango-controls/cppTango#242]
Memory leak in DS for R/W spectrum string attribute if you use dynamic allocation and ask Tango to delete
memory through the forth arg of the Attribute::set_value() method

Fixed in SVN repo

Reported by: taurel

Original Ticket: [tango-cs/bugs/801](https://sourceforge.net/p/tango-cs/bugs/801)

**Comment by hardion** [comment]
To be closed

**Comment by bourtemb** [comment]
Fixed in tango 9.2.5
