### ISSUE TITLE
Bugs in DevicePipeBlob management

### ISSUE THREAD

**Issue by tango-tickets-migrator** [tango-controls/cppTango#243]
Several bugs in DevicePipeBlob management:
1 - Missing exception when trying to extract data from a DevicePipeBlob not initialized from a device pipe
2 - Crash when inserting a DevicePipeBlob in a blob with retrievel of the data element by its name or when creating a Data element with the inner DevicePipeBlob

Fixed in SVN repo

Reported by: taurel

Original Ticket: [tango-cs/bugs/802](https://sourceforge.net/p/tango-cs/bugs/802)

**Comment by bourtemb** [comment]
Fixed in tango 9.2.5
