### ISSUE TITLE
push event performance issue

### ISSUE THREAD

**Issue by tango-tickets-migrator** [tango-controls/cppTango#244]
When using push_change_event and push_archive_event there is a big difference in performances if using it with the "criteria managed by library" option (second argument of set_xxx_event) set to true or false.
In the first case there is a lot of CPU consuption in the push_xxx_event execution also when thresholds criteria for sending the event are not met. Furthermore there is a quite high variance in the execution time of push_xxx_event.
Finally in both cases there is an increase of CPU consuption in the push_xxx_event execution if there are client subscribed to the event.

Attached there is a document with some results on a real case and a simple test device server to reproduce.

Note: in the second case threshold are read from the DB only at startup of the server.

Reported by: scalamera

Original Ticket: [tango-cs/bugs/803](https://sourceforge.net/p/tango-cs/bugs/803)

**Comment by bourtemb** [comment]
This problem should be solved in Tango 9 LTS with PR #430

**Comment by bourtemb** [comment]
Should be solved with the combination of PR #430 and #458
