### ISSUE TITLE
Missing check in  Dserver::zmq_event_subscription_change() method

### ISSUE THREAD

**Issue by tango-tickets-migrator** [tango-controls/cppTango#245]
A check  on get_alternate_endpoint() size should be added before the following line at the end of  Dserver::zmq_event_subscription_change() method

tmp_str = ev->get_alternate_event_endpoint()[loop];

The check is present a bit above in similar code of the same method.
A crash on Windows (only in DEBUG mode) has been reported by SangKee Lee on the tango-controls forum because of this issue.
(http://www.tango-controls.org/community/forum/c/development/c/set_change_event-with-nodb-option-detect-not-working/?page=2#post-1739)

Reported by: bourtemb

Original Ticket: [tango-cs/bugs/805](https://sourceforge.net/p/tango-cs/bugs/805)

**Comment by hardion** [comment]
To be closed

**Comment by bourtemb** [comment]
Fixed in Tango 9.2.5
