### ISSUE TITLE
DevShort attribute change event has wrong data_type

### ISSUE THREAD

**Issue by tango-tickets-migrator** [tango-controls/cppTango#248]
If a tango-9 client subscribes for change_event of a DevShort attribute on a tango-8 server, the event_type returned by attr_value->get_type() is DATA_TYPE_UNKNOWN (100).
All other 8 vs 9 combinations report the correct value DEV_SHORT (2).
Tested on ubuntu linux 10.04 and 14.04, 32 and 64 bits, all combinations.
The problem becomes evident when using automatic tools for extracting and formatting the attibute value pushed by the event system, which detects dynamically the type of the received attribute.
Notice that the first event , triggered by subscribe_event call or by automatic resusbscription triggered by the heartbeat system, always has the correct data type (2).

Reported by: claudioscafuri

Original Ticket: [tango-cs/bugs/816](https://sourceforge.net/p/tango-cs/bugs/816)

**Comment by hardion** [comment]
To be closed (sorry for the spamming)

**Comment by bourtemb** [comment]
Fixed in Tango 9.2.5
