### ISSUE TITLE
Group state() and status()

### ISSUE THREAD

**Issue by tango-controls-bot** [tango-controls/cppTango#252]
I think it would be nice and useful that tango groups had state() and status() commands. I'm thinking on:
state(): returns the worst state of all the devices in the group (ON if all ON)
status(): something like "All devices OK" if all OK or "Devices XXX are not ON"

Reported by: jairomoldes

Original Ticket: [tango-cs/feature-requests/25](https://sourceforge.net/p/tango-cs/feature-requests/25)

**Comment by andygotz** [comment]
@jairomoldes  sounds useful but how to define the result of "adding" state or status of multiple devices?

**Comment by Ingvord** [comment]
@andygotz , @jairomoldes IMHO State and Status of a Group must be simply an array of States and Statuses
