### ISSUE TITLE
Know when memorized attributes have been applied

### ISSUE THREAD

**Issue by tango-controls-bot** [tango-controls/cppTango#253]
I would like to have a callback for the DS that gets executed after the memorized-and-write-to-hardware-at-init attributes have been applied to the DS.

Use case: Imagine a continuous acquisition DS. You can have two states: During one you can configure the device, on the other you can't as it is getting data. I want to use memorized attributes to store the settings and I also want an "AutoStart" property that let's me atomatically go to the "acquiring" state after initialisation. But, when should I go to the "acquiring" state? It can't be done on "init_device" because then I will be on the "acquiring" state so the application of memorized attributes will fail. But I could just start the device in the normal "config" state on "init_device", then let the memorized attributes apply, and finally get a callback "attributes applied" so I can decide to change my state to "acquiring".

I attach a sample implementation of this.

Maybe this could be implemented in another way and the name of the virtual method could be something not related to memorized attributes like "all_initialization_finished" so it seems more generic.

Reported by: ollupac

Original Ticket: [tango-cs/feature-requests/27](https://sourceforge.net/p/tango-cs/feature-requests/27)

**Comment by andygotz** [comment]
Is this feature still needed?
