### ISSUE TITLE
Let customize destruction procedure

### ISSUE THREAD

**Issue by tango-tickets-migrator** [tango-controls/cppTango#256]
Let device programmer customize destruction procedure making delete_dev() virtual. Tango already provides that chance for construction procedure (thanks to device_factory() which it is virtual) so it could be reasonable and usefull make that API *symmetric*.

Reported by: sogliola

Original Ticket: [tango-cs/feature-requests/80](https://sourceforge.net/p/tango-cs/feature-requests/80)

**Comment by andygotz** [comment]
Seems to be done. Please re-open if necessary.
