### ISSUE TITLE
Upper/lower case management 

### ISSUE THREAD

**Issue by tango-tickets-migrator** [tango-controls/cppTango#26]
When Devices names are mixing uppercases and lower 
cases, the operation of adding and/or removing devices 
from the logged devices is unsuccessfull. 
A message indicates an error in the history window

Reported by: buteau

Original Ticket: "tango-cs/bugs/3":https://sourceforge.net/p/tango-cs/bugs/3

**Comment by bourtemb** [comment]
This very old issue seemed to have been fixed (probably a long time ago)...
