### ISSUE TITLE
Can not compile libtango on Ubuntu 16 using libzmq3-dev package from apt

### ISSUE THREAD

**Issue by Ingvord** [tango-controls/cppTango#273]
Error message

```
[ 17%] Building CXX object cppapi/client/CMakeFiles/client_objects.dir/zmqeventconsumer.cpp.o
/home/ingvord/Projects/org.tango/git/cppTango/cppapi/client/zmqeventconsumer.cpp: In member function ‘virtual void* Tango::ZmqEventConsumer::run_undetached(void*)’:
/home/ingvord/Projects/org.tango/git/cppTango/cppapi/client/zmqeventconsumer.cpp:186:18: error: cannot convert ‘zmq::socket_t’ to ‘void*’ in assignment
  items[0].socket = *control_sock;
                  ^
/home/ingvord/Projects/org.tango/git/cppTango/cppapi/client/zmqeventconsumer.cpp:187:18: error: cannot convert ‘zmq::socket_t’ to ‘void*’ in assignment
  items[1].socket = *heartbeat_sub_sock;
                  ^
/home/ingvord/Projects/org.tango/git/cppTango/cppapi/client/zmqeventconsumer.cpp:188:18: error: cannot convert ‘zmq::socket_t’ to ‘void*’ in assignment
  items[2].socket = *event_sub_sock;
                  ^
/home/ingvord/Projects/org.tango/git/cppTango/cppapi/client/zmqeventconsumer.cpp: In member function ‘bool Tango::ZmqEventConsumer::process_ctrl(zmq::message_t&, zmq::pollitem_t*, int&)’:
/home/ingvord/Projects/org.tango/git/cppTango/cppapi/client/zmqeventconsumer.cpp:1063:47: error: cannot convert ‘zmq::socket_t’ to ‘void*’ in assignment
                 poll_list[old_poll_nb].socket = *tmp_sock;

```

```
Linux ingvord-VirtualBox 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

libzmq3-dev 4.1.4-7

**Comment by Ingvord** [comment]
Current work-around:

Download, compile and install [zmq-4.0.5](https://github.com/zeromq/zeromq4-x/releases/tag/v4.0.5)

Download and copy into zmq-4.0.5 installation folder, e.g. /usr/local/zmq-4.0.5/include, *.hpp files from [cppzmq](https://github.com/zeromq/cppzmq)

**Comment by jkotan** [comment]
I have the same problem for debian 9 (stretch).

**Comment by Ingvord** [comment]
@jkotan did the workaround work out for you?

**Comment by jkotan** [comment]
Sorry,  I've tried. I have switched with my tests from `stretch` back to `jessie` and decided to wait with them for a proper implementation for zmq in tango, i.e. an adapter or factory for different zmq APIs.

**Comment by Ingvord** [comment]
I mean good point on adapter pattern

**Comment by t-b** [comment]
Is that the offical zeromq API you are using? The socket type from https://github.com/zeromq/libzmq is void*.

**Comment by andygotz** [comment]
For now only zmq 4.0.5 is officially supported.

**Comment by Ingvord** [comment]
Well, as far as I remember. We are actually using https://github.com/zeromq/cppzmq which is not pure libzmq I believe, but a binding

**Comment by andygotz** [comment]
@t-b  the situation is even more complicated. I just checked on  Ubuntu 17.10 and here tango is using libzmq.so.5.1.1 and works. So apparently my statement that tango has been tested only with 4.0.0 of zmq is not true. At least it works with more recent versions like 5.1.1. This does not mean it works with all recent versions. Let us know if it works with zmq 4.0.8.

**Comment by bourtemb** [comment]
#421 addresses this issue.
The solution to this issue is to install [cppzmq](https://github.com/zeromq/cppzmq) (v4.2.2 for instance) and to use -DCPPZMQ_BASE=<cppzmq install base folder> when compiling libtango.
With this solution, Travis CI tango-9-lts tests are passing for libzmq3-dev Debian packages from wheezy-backports, jessie and stretch (Debian 7, Debian 8 and Debian 9).
