### ISSUE TITLE
Segfault in polled device at startup

### ISSUE THREAD

**Issue by tango-tickets-migrator** [tango-controls/cppTango#298]
I have run into a segfault that seems to be related to the fix of bug #814. So it might not happen if that patch is not applied, I have not tested that.

The problem can be reproduced by these steps:
- Add a new server and device to the DB (I have not been able to make it happen unless it's the first time the server is run after being added)
- Configure polling on e.g. State, by writing the "polled_attr" property. The interval does not seem to matter.
- Start the server. It will sometimes (maybe 1 time out of 10) immediately segfault.

I'm attaching a short python script that performs this test. It probably needs to be run a few times before it catches the problem. It assumes the TangoTest device to be available in the path.

By some debugging, I've come to the conclusion that the issue comes from line 641 in blackbox.cpp. It assumes that if the call does not come from polling or from an user thread, it's from a client. But the host may also be "init" under some circumstances (I guess right after startup) and in that case a null pointer error happens a bit later. At least, modifying the line to something like:

```
if (box[insert_elt].host_ip_str[0] == 'p' || box[insert_elt].host_ip_str[0] == 'u' ||
      box[insert_elt].host_ip_str[0] == 'i')  // this is the new part
```

appears to solve the problem.

Reported by: johfor

Original Ticket: [tango-cs/bugs/818](https://sourceforge.net/p/tango-cs/bugs/818)

**Comment by bourtemb** [comment]
Fixed in Tango 9.2.5
