### ISSUE TITLE
Swapped origin and desc in some versions of Tango::Except::throw_exception.

### ISSUE THREAD

**Issue by tango-tickets-migrator** [tango-controls/cppTango#301]
In except.h, origin and desc are sometimes swapped when being copied to the DevErrorList entry. For example, lines 490-491 are
`errors[0].origin = CORBA::string_dup(desc);`
`errors[0].desc = CORBA::string_dup(origin.c_str());`
The same occurs also on lines 697, 844, 1262, 1406, 1481 and 1636.

Regards,
Josef

Reported by: jcibulka

Original Ticket: [tango-cs/bugs/822](https://sourceforge.net/p/tango-cs/bugs/822)

**Comment by Ingvord** [comment]
Fixed in #305
