### ISSUE TITLE
Crash when executing a command from a thread on an in-process device

### ISSUE THREAD

**Issue by tango-tickets-migrator** [tango-controls/cppTango#302]
Using Tango 9.2.2:
Crash is a null-pointer access in Tango's blackbox.cpp:
omni_thread::value_t *ip = omni_thread::self()->get_value(key);

self() returns nullptr in this case.

To reproduce, let any command do something like this:

```
std::thread thread([this]() {
    std::string target = this->device_name;
    auto proxy = std::make_shared<Tango::DeviceProxy>(target);
    proxy->command_inout("status");
});

thread.join();
```

Reported by: schneidemwe

Original Ticket: [tango-cs/bugs/823](https://sourceforge.net/p/tango-cs/bugs/823)

**Comment by bourtemb** [comment]
Fixed in Tango 9.2.5
