### ISSUE TITLE
Please adapt tango to zeromq 4.2.0

### ISSUE THREAD

**Issue by picca** [tango-controls/cppTango#312]
Hello guyes,

Here I put the information I have about this problem, here

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=844479

It seems to me that it will be difficult to keep zeromq < 4.2.0 for Debian 9.

Can you try to find a fix before the freeze of Debian ?

thanks

Fred

**Comment by nleclercq** [comment]
Hey Fred, 
That's a challenging request! 
The recent change in zmq data alignment is a bad joke for us.
N
