### ISSUE TITLE
Events do not work when subscribing to events with FQDN containing localhost or network aliases or multiple network interfaces ...

### ISSUE THREAD

**Issue by bourtemb** [tango-controls/cppTango#315]
This issue is described in the following Tango forum topic:
http://www.tango-controls.org/community/forum/c/development/python/event-system-problem

The events do not work as expected when a client subscribe to events using FQDN starting with localhost or when there are multiple network interfaces or aliases.

The symptom is that events are not received and the client gets an exception once every 10 seconds due to the heartbeat timeout. The origin of the problem is that the server and client separately generate the event fliter name used by zmq. Because the client and server are on different hosts potentially or in different languages they resolve the hostname differently and therefore have different zmq filters. The solution is for the client to use the same zmq filter as they server.

A workaround is to use the real machine name instead of localhost.

This was reproduced in C++.
To be checked in Java too.

**Comment by andygotz** [comment]
A first attempt at solving this problem was done in the PR #385 but @Ingvord proposes to not use this PR and to start a new one.

**Comment by Ingvord** [comment]
@bourtemb, could you please test #404 in the conditions mentioned in this issue? If it is OK we can merge #404 into the master and backport it into tango-9-lts

**Comment by bourtemb** [comment]
This should be fixed in #423 (available in cppTango 9.3.0).
Closing this issue. Please reopen if you still experience this problem with cppTango >= 9.3.0.
