### ISSUE TITLE
remove RcsId

### ISSUE THREAD

**Issue by andygotz** [tango-controls/cppTango#322]
The RcsId variable is defined in many source files (80+)but never used. It generates a compiler warning when compiling Tango. RcsId is a vestige left over from the RCS revision system (before SVN) and was used to determine the version of each file individually. This is not needed any more because we release all files in the library together. 

I propose to remove all unused occurrences of RcsId.

**Comment by t-b** [comment]
It would be nice if pogo also learned to not output the `RcsId` line.

**Comment by Ingvord** [comment]
For the future: if you have some changes - create Pull Request without creating an issue. Otherwise it simply duplicates the entity.
