### ISSUE TITLE
pointer-cast-size-mismatch attrgetsetprop.cpp:200

### ISSUE THREAD

**Issue by picca** [tango-controls/cppTango#339]
Hello,

while preparing the tango package of the 9.2.5~rc5, I got this error.

You can find other warning errors here, which are more packaging related.

https://qa.debian.org/bls/packages/t/tango.html

Cheers

**Comment by Ingvord** [comment]
Is this urgent? I mean, is it possible to provide debian package with this error?

**Comment by picca** [comment]
> Is this urgent? I mean, is it possible to provide debian package with this error?

I think that plenty of packages are distributed with bug :), so it is possibleto provide tango 9.2.5 with this bug.

Now I do not know if this can be fixed with a one liner for the final release of 9.2.5 in january.


Cheers


Fred

**Comment by andygotz** [comment]
Needs to be done in LTS9 as well. If done then please close this issue. Thanks!

**Comment by bourtemb** [comment]
Done on Tango 9 LTS too (PR #406).
Closing this issue.
