### ISSUE TITLE
Device ALARM state issue with forwarded attribute associated with a polled root attribute

### ISSUE THREAD

**Issue by bourtemb** [tango-controls/cppTango#386]
Let's consider the following setup:
_my/fwd/dev/testfwd_ attribute is associated with root attribute _my/other/dev/root_.
_my/other/dev/root_ is polled.
In this case, if _my/fwd/dev_ is ON and _my/other/dev/root_ quality factor switches between VALID and ALARM, the state of _my/fwd/dev_ will not switch correctly to ALARM when _my/other/dev/root_ quality factor is ALARM, unless a client explicitly read _my/fwd/dev/testfwd_ attribute.
This problem is due to the fact that this case is handled by the polling thread for normal attributes, but the polling does not occur in the same device for the forwarded attributes... 
So, in this case, _my/fwd/dev_ should subscribe to _my/other/dev/root_ (it might be already the case, I don't know yet this part of the code) and react when there is a root attribute quality factor change.

**Comment by bourtemb** [comment]
(automatically?) Closed by mistake?

**Comment by Ingvord** [comment]
Sorry! It was closed accidentally... should be #396  in the comment
