### ISSUE TITLE
tango_const.h not installed

### ISSUE THREAD

**Issue by jkotan** [tango-controls/cppTango#390]
Hi,

it looks like after https://github.com/tango-controls/cppTango/issues/389  cmake does not install `tango_const.h`, i.e. building pytango I get

    creating build/temp.linux-x86_64-2.7/home/jkotan/sources/pytango/ext/server
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DPYTANGO_NUMPY_VERSION="1.8.2" -DPYTANGO_HAS_UNIQUE_PTR=1 -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/home/jkotan/testtango/include -I/home/jkotan/sources/pytango/ext -I/home/jkotan/sources/pytango/ext/server -I/usr/include/python2.7 -c /home/jkotan/sources/pytango/ext/api_util.cpp -o build/temp.linux-x86_64-2.7/home/jkotan/sources/pytango/ext/api_util.o -std=c++0x
    In file included from /home/jkotan/testtango/include/tango/client/dbapi.h:32:0,
		     from /home/jkotan/testtango/include/tango.h:93,
		     from /home/jkotan/sources/pytango/ext/api_util.cpp:13:
    /home/jkotan/testtango/include/tango/client/devapi.h:32:38: fatal error: tango/server/tango_const.h: No such file or directory
     #include <tango/server/tango_const.h>
					  ^
    compilation terminated.

**Comment by Ingvord** [comment]
@jkotan thanks for the report! I think we have to client-library (pytango?) compilation as an integration test
