### ISSUE TITLE
Inserting const C string in DeviceData

### ISSUE THREAD

**Issue by taurel** [tango-controls/cppTango#395]
Inserting a const C string in a DeviceData instance does not work
(Tango::DeviceData din;
din << "MyString";)

This is due to the inserter method in the DeviceData.h file which is defined for type
char *& or const char *&. The reference must be removed

**Comment by Ingvord** [comment]
I would remove support of **char*** from API at all, as C++ way is to use std::string.

**Comment by bourtemb** [comment]
When you say removing support for char *, do you mean removing:
`DeviceData::operator << (char *datum)`
and
`DeviceData::operator << (const char *datum)`
or just the first one?

Still I find it convenient to be able to do:
```
DeviceData dd;
dd << "My wonderful string";

```

**Comment by Ingvord** [comment]
I mean leave only string. The later should compile due to implicit conversion.

**Comment by bourtemb** [comment]
Well, this is what I thought too.
I already tried to keep only the string insertion operator.
It compiles but at run time time, the wrong insertion method is called (operator << (bool) ).

**Comment by bourtemb** [comment]
Removing them will also create some compatibility issues.
Tango::DevString is actually a char *
CORBA is also using char * when dealing with DevStrings.
So I think we should not remove them.

**Comment by Ingvord** [comment]
Well, I agree - not in Tango 9 LTS ;)
