### ISSUE TITLE
Device_6Impl constructor missing default values

### ISSUE THREAD

**Issue by bourtemb** [tango-controls/cppTango#411]
This issue refers to the following comment:
https://github.com/tango-controls/cppTango/pull/357#discussion_r132729427

In Device_5Impl version, there are some default values defined for desc, dev_state and dev_status arguments.
This is important if you want to be backward compatible with servers generated with Pogo which generates code like the following for a Tango class named TestCmds:

    TestCmds::TestCmds(Tango::DeviceClass *cl, const char s, const char d)
    : TANGO_BASE_CLASS(cl, s, d)
    {
    /----- PROTECTED REGION ID(TestCmds::constructor_3) ENABLED START -----/
    init_device();

    /----- PROTECTED REGION END -----/ // TestCmds::constructor_3
    }

**Comment by Ingvord** [comment]
Closed via #420
