### ISSUE TITLE
command.h name conflicts with other builds

### ISSUE THREAD

**Issue by mike-a-smith** [tango-controls/cppTango#434]
Building u-boot on machines with tango headers installed fails due to the presence of command.h in /usr/include or /usr/local/include.  Any change this file can be renamed?  It looks like it is only referenced once in tango.h

**Comment by t-b** [comment]
@mike-a-smith I have here tango headers in /usr/local/include/tango only. There will always be some overlap in filenames between projects. My solution for this is usually to move the code referencing conflicting headers into a different translation unit.

**Comment by t-b** [comment]
This is solved in upcoming tango source distribution 9.3.3.
