### ISSUE TITLE
Add server_init_hook() method

### ISSUE THREAD

**Issue by bourtemb** [tango-controls/cppTango#498]
Following discussion from https://github.com/tango-controls/TangoTickets/issues/7 and offline discussions, we came to the conclusion it would be useful to add a new server_init_hook() method (in the same spirit as always_executed_hook() method) at device level which would be called once the device server admin device is exported.
This would allow for instance for the different devices to subscribe to events at server startup on attributes from other devices of the same device server with stateless parameter set to false. The subscription should work in this case since the admin device would be exported when the hook would be called.

**Comment by t-b** [comment]
Closed via #551.
