### ISSUE TITLE
Deploy automatically Doxygen documentation to Github pages

### ISSUE THREAD

**Issue by bourtemb** [tango-controls/cppTango#545]
It would be great to generate and deploy automatically the Doxygen documentation to cppTango GitHub pages using Travis, when a new tag is created on tango-9-lts branch for instance.
Here are some links which might be useful to implement this:

https://gist.github.com/bmegli/e22ba525dda0b197b2d4440d08f43ae2
https://docs.travis-ci.com/user/deployment/pages/

**Comment by t-b** [comment]
Todos:
- [ ] Make `doc` a target with dependencies
- [ ] Keep the source tree clean
- [ ] Fix doxygen warnings and make warnings an error, output warnings to file
- [ ] Add to CI using gitlab actions
- [ ] Move docu repo from https://github.com/tango-controls/cppTango-docs to gh-pages branch of this repo
