### ISSUE TITLE
Forwarding State

### ISSUE THREAD

**Issue by lorenzopivetta** [tango-controls/cppTango#550]
Hi,
is there any issue with forwarding the State attribute? Consider the following scenario:
- device "lorenzo/uno/uno" provides attribute "uno" (DevDouble,rw) and "anotherState" (DevState,rw).
- device "lorenzo/due/due" is configured with the following forwarded attirbutes:
    1) unoFwd with __root_attr lorenzo/uno/uno/uno 
    2) anotherStateFwd with __root_attr lorenzo/uno/uno/anotherState
    3) unoStateFwd with __root_attr lorenzo/uno/uno/State

Reading the forwarded attribute from device "lorenzo/due/due" works for case 1 and 2; events work too.
Reading forwarded attribute from device "lorenzo/due/due" for case 3 results in a segmentation:

...
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb0dfab70 (LWP 16669)]
0xb7d549ae in void Tango::FwdAttribute::set_local_attribute<Tango::DevVarStateArray>(Tango::DeviceAttribute&, Tango::DevVarStateArray*&) ()
   from /usr/local/tango-9.3.3-debug/lib/libtango.so.9

Tests with Tango 9.3.3, OmniORB 4.2.3, ZeroMQ 4.0.8

**Comment by bourtemb** [comment]
Hi @lorenzopivetta 

Thank you very much for the bug report. I can reproduce the problem.
This bug does not occur when forwarding a DevState Read Only or RW scalar attribute which is different than the attribute named "State".
