### ISSUE TITLE
Investigate sonar issues

### ISSUE THREAD

**Issue by t-b** [tango-controls/cppTango#585]
From https://github.com/tango-controls/cppTango/pull/562#pullrequestreview-269094756

> There are some strange messages at the end of Travis Debian 8 build with >SONAR_SCANNER=ON :
>.travis/sonar.sh: line 11: sonar-scanner: command not found
>This might help us to find out why we don't get very often sonarcloud notifications.

**Comment by Ingvord** [comment]
FYI #584

**Comment by t-b** [comment]
That looks like a temporarily hickup. Closing for now.
