### ISSUE TITLE
Use automatic code formatting

### ISSUE THREAD

**Issue by t-b** [tango-controls/cppTango#586]
Inspired from https://github.com/tango-controls/cppTango/pull/581#issuecomment-516828044

Situation:
 The code base is currently manually formatted and indented. So it sometimes looks like

![grafik](https://user-images.githubusercontent.com/1185677/62293817-b273a580-b469-11e9-82c4-8e552fe837d4.png)

This is of course not nice as it forces the developer to manually indent using mixed indentation. And it is also a waste of developers time.

Proposal:
- [ ] Add clang-format file from https://github.com/AllenInstitute/ZeroMQ-XOP/blob/master/src/.clang-format
- [ ] Add a cmake target which calls clang-format
- [ ] Start discussion about how formatting should be done
- [ ] Make **1** commit changing all the C++ code to use the new formatting
- [ ] Document how users can ignore this commit when blaming using the new git blame feature available from git 2.23, see also https://github.com/gitster/git/commit/ae3f36dea16e51041c56ba9ed6b38380c8421816.
- [ ] Add a travis job which ensure that the PR matches our code formatting. Passing this check is *mandatory* for all PRs.
- [ ] Finalize formatting discussion

**Comment by Ingvord** [comment]
+1

My 50 cents: auto-formatting procedure must be as simple as `Ctrl+Alt+L` in CLion

**Comment by bourtemb** [comment]
> 
> 
> +1
> 
> My 50 cents: auto-formatting procedure must be as simple as `Ctrl+Alt+L` in CLion

It looks like CLion already supports clang-format:
https://www.jetbrains.com/help/clion/clangformat-as-alternative-formatter.html
