### ISSUE TITLE
Device server class inheriting from 4Impl does not send events

### ISSUE THREAD

**Issue by tiagocoutinho** [tango-controls/cppTango#591]
A [bug was reported in the PyTango project](https://github.com/tango-controls/pytango/issues/311) mentioning that a device server using PyTango 9.3.2 and Tango 9.3.x was unable to send manual events.
@jairomoldes noticed that the device class was inheriting from Device_4Impl instead of Device_5Impl. It seems to be the cause of the problem.

We were able to reproduce it in C++ (see attached code).

The same code worked well with Tango C++ 9.2.5

The best practice is to inherit from LastestDeviceImpl (PyTango original API) or from the TANGO_BASE_CLASS (in case of C++). But for old device servers it would be nice if they
still work without changes in the code.

IMHO this is not critical.
[Test.zip](https://github.com/tango-controls/cppTango/files/3702349/Test.zip)

**Comment by bourtemb** [comment]
@tiagocoutinho, this bug looks very similar to #492 which was  present in cppTango 9.3.2 and for which a fix was provided  ( #531 ) (in cppTango 9.3.3).
Is PyTango 9.3.2 using cppTango 9.3.2 as the name is suggesting?
Did you try with cppTango 9.3.3 or cppTango 9.3.2?
