### ISSUE TITLE
appveyor: Add support for automatic uploading of releases to github

### ISSUE THREAD

**Issue by t-b** [tango-controls/cppTango#602]
> @bourtemb Regarding "Add Windows installers as assets to the GitHub release": Is that currently done with a script (where is that?) or if not, is it worth having one?

I think it was done manually the last time. Automating this process would be much better of course.

> Appveyor does also support that out of the box. See https://www.appveyor.com/docs/deployment/github/.

Good idea. I think we should try that.

_Originally posted by @bourtemb in https://github.com/tango-controls/cppTango/issues/594#issuecomment-545540317_

**Comment by t-b** [comment]
According to @bourtemb this is not working.

**Comment by t-b** [comment]
In case the automatic uploading is not working, here is what needs to be done semi-manually:
- Build: https://ci.appveyor.com/project/NexeyaSGara/cpptango-37ylj
- Wait until build is finished
- Go to https://ci.appveyor.com/account/NexeyaSGara/environment/48608/settings (we are deploying to an environment)
- Add the tag you wish to deploy against (can but doesn't have to exist)
- Add a personal access token with `repo` scope
- Deploy each build

**Comment by t-b** [comment]
Check if it works in https://github.com/tango-controls/cppTango/releases/tag/9.3.4-rc5 and if yes, forward port the new access token.

**Comment by bourtemb** [comment]
>     * [ ]  Check if it works in https://github.com/tango-controls/cppTango/releases/tag/9.3.4-rc5 and if yes, forward port the new access token.

@t-b, did it work or did you use the semi-manual method again?

**Comment by t-b** [comment]
Nope I used the semi-manual method again. I need to get that working in a separate test repo. ATM I don't understand why it is not working.

**Comment by t-b** [comment]
@bourtemb So I'm getting closer. https://ci.appveyor.com/project/bourtemb/cpptango-tt3w8/branch/tango-9-lts/job/0gbmxfm3i43qo35y did not work as the auth_token was wrong. The error message 

```
Error creating GitHub release: Provider setting not found or it's value is empty. If secure setting is used please check that value was encrypted (or YAML was exported) while being logged under correct account.
Parameter name: auth_token
```

suggests that I can not encrypt a secret for a project running under your account. Can you make me a collaborateur on your appveyor project?

**Comment by t-b** [comment]
Or even better move it to a newly created tango-controls orga on appveyor?

**Comment by bourtemb** [comment]
I added cppTango team as admin for cppTango project from my appveyor account.
Would that be sufficient for you, @t-b ?
I have no idea how to move it to tango-controls orga appveyor.
I think there are currently at least 3 appveyor accounts which are used for building cppTango PR with appveyor: my account, @NexeyaSGara and @Ingvord 's accounts.

**Comment by t-b** [comment]
@bourtemb THanks. That should do the trick for now.
