### ISSUE TITLE
Remove second database instance from tests

### ISSUE THREAD

**Issue by mliszcz** [tango-controls/cppTango#630]
Hi all,

PR #608 added a second database instance to the tests to reproduce a scenario where device names from a group are resolved against wrong TANGO_HOST database.

After some testing it looks like it is possible to reproduce the issue with just one database, if TANGO_HOST is not specified (or empty).
* without correction: `tango://host2:port/dev/*` pattern will be resolved to `dev/a/b` which needs TANGO_HOST to be specified
* with the correction, `tango://host2:port/dev/*`  is resolved correctly to `tango://host2:port/dev/a/b`  and the library does not even look for TANGO_HOST variable.

I propose to remove the second database instance to simplify bringing #568 (which needs to start fresh database for each test) up to date.

@bourtemb, @t-b, @Ingvord is it ok for you? If yes, I'll send a PR and remove the second db (TANGO_HOST2).

**Comment by bourtemb** [comment]
> I propose to remove the second database instance to simplify bringing #568 (which needs to start fresh database for each test) up to date.
 
Fine by me.

**Comment by t-b** [comment]
@mliszcz Sounds good!

**Comment by Ingvord** [comment]
+1

**Comment by t-b** [comment]
Closed via #630.
