### ISSUE TITLE
get_host_info().host is " "

### ISSUE THREAD

**Issue by tango-controls-bot** [tango-controls/cppTango#65]
the get_host_info() method of the data base object returns DbServerInfo with the host field being " ".

Reported by: lkrause2

Original Ticket: "tango-cs/bugs/189":https://sourceforge.net/p/tango-cs/bugs/189

**Comment by bourtemb** [comment]
Hi,

I'm going through the old tickets... It is not clear to me whether something still needs to be done for this ticket...
@taurel seemed to think at that time (in 2008) it would be safer to remove the two Database class methods called get_server_info() and put_server_info() from pyTango...
Is this comment still valid? These method still seem to be there in PyTango
Is there anything to do?
@tiagocoutinho , do you think there is anything to be done?
Should this ticket be closed? Should we create a new PyTango issue?

Thanks for your feedback!

**Comment by bourtemb** [comment]
I think the cleanest would be to add a row in server DB table during the call to db_export_device if the row for this server does not exist yet, before the UPDATE statement on server DB table.
db_export device is currently executing an UPDATE query on server DB table. This will do nothing in the current version if no row with this server name was previously created (with db_put_server_info method), which leads to DataBase::get_server_info().host being empty in some cases, even though the information about the host is known.
