### ISSUE TITLE
sys/tg_test/1 with enumLables

### ISSUE THREAD

**Issue by HFRibeiro** [tango-controls/cppTango#660]
Hi,
Maybe not the right place to ask this, but is there any planning on adding enumLables attribute on the sys/tg_test/1 device?
Maybe I'm wrong but I'm not seeing any at this point there.

Thanks.

**Comment by bourtemb** [comment]
Hi @HFRibeiro 

Thanks for creating this issue.
I created a new issue in TangoTestGithub repo: https://github.com/tango-controls/TangoTest/issues/7
Please feel free to comment & contribute there.
