### ISSUE TITLE
Prepare 9.3.4-rc4

### ISSUE THREAD

**Issue by t-b** [tango-controls/cppTango#667]
- [x] Merge PRs
  - [x] https://github.com/tango-controls/cppTango/pull/664
  - [x] https://github.com/tango-controls/cppTango/pull/665
  - [x] https://github.com/tango-controls/cppTango/pull/672
- [x] Tag repo with 9.3.4-rc4
- [x] Upload appveyor windows builds
- [x] Merge https://github.com/tango-controls/TangoSourceDistribution/pull/71
- [x] ping picca

**Comment by t-b** [comment]
@picca we have  a new release candidate

**Comment by picca** [comment]
Uploaded into experimental.

So if you could test it and give me some feed back :)
here the build log

https://buildd.debian.org/status/package.php?p=tango&suite=experimental

there is bunch of warning during the build

cheers

**Comment by t-b** [comment]
Thanks! Is https://salsa.debian.org/science-team/tango/-/jobs/711621 the current lintian output?

**Comment by picca** [comment]
yes :).


________________________________________
De : Thomas Braun [notifications@github.com]
Envoyé : samedi 2 mai 2020 14:32
À : tango-controls/cppTango
Cc : PICCA Frederic-Emmanuel; Mention
Objet : Re: [tango-controls/cppTango] Prepare 9.3.4-rc4 (#667)

Thanks! Is https://salsa.debian.org/science-team/tango/-/jobs/711621 the current lintian output?
