### ISSUE TITLE
C++17 compatibility: std::binary_function removed

### ISSUE THREAD

**Issue by ltjax** [tango-controls/cppTango#680]
std::binary_function has been removed in C++17:

https://en.cppreference.com/w/cpp/utility/functional/binary_function

g++ seems to ignore this removal, but VS2019 fails to compile a tango device with C++17 enabled. It's only used for two functors: WantedProp and WantedClassAttr. It should be relatively easy to remove and still have cppTango compile (use std::bind instead of std::bind2nd, which has also been removed - or a lambda), but removing it from the public interface might break some clients.

**Comment by t-b** [comment]
We can remove any references to `std::binary_function` in the tango-9-lts branch. The next release (9.4) will not be ABI compatible, and minor API changes are also okay.
