### ISSUE TITLE
Travis CI potential optimization: No need to clone and install tango_admin when RUN_TESTS=OFF

### ISSUE THREAD

**Issue by bourtemb** [tango-controls/cppTango#710]
When RUN_TESTS is set to OFF, there is no need for the Travis jobs to clone and install tango_admin.

**Comment by t-b** [comment]
@bourtemb I think we also only need

https://github.com/tango-controls/cppTango/blob/c3d153f4f843814e971612c8589b092f24846c5e/.travis.yml#L43-L44

if we are running the tests or?

**Comment by bourtemb** [comment]
> @bourtemb I think we also only need
> 
> https://github.com/tango-controls/cppTango/blob/c3d153f4f843814e971612c8589b092f24846c5e/.travis.yml#L43-L44
> 
> if we are running the tests or?

I guess you meant " I think we also don't need".
In this case, right you are!
