### ISSUE TITLE
Replace deprecated std functions

### ISSUE THREAD

**Issue by bourtemb** [tango-controls/cppTango#714]
Compilation attempts on Mac OS X Sierra (https://www.tango-controls.org/media/pybb_upload/attachments/aed90082-cacf-4238-a2ac-f4deced5a0fa.txt) exposed some compilation errors due to the usage of some deprecated std functions like std::func_ptr and std:bind2nd

We should replace these functions in tango-9-lts branch

**Comment by t-b** [comment]
I guess apple turns on `-Wdeprecated-implementations` for clang on MacOSX. See also https://releases.llvm.org/9.0.0/tools/clang/docs/DiagnosticsReference.html#wdeprecated-implementations. We could do the same in the warnings as errors job.
