### ISSUE TITLE
GroupAttrReplyList extraction no longer throw an exception with INVALID data

### ISSUE THREAD

**Issue by JeanLucPons** [tango-controls/cppTango#754]
Hello,
It seems that the extraction of a GroupAttrReplyList does not throw an exception when trying to extract invalid data.
In the following case, i would expect an exception at line 949 but i get a segfault at line 951 with an empty array.
The arl array is a Tango::GroupAttrReplyList arl[].
The corresponding attribute data is INVALID.
It is normal ? This server never crashed here and this crash happened when I recompiled it with Tango 9.3.4-rc6.
Thanks for help

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `BrillianceBPMAll all'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055f9fc4cf2de in AttributeCombiner_ns::AttributeCombiner::READG<int> (this=0x55f9fcc2bd40, attr=..., 
    value=@0x55f9fd0c2a88: 0, item=0x55f9fd0c2a00, arl=0x7f039fffdc60)
    at ../../../../calculation/AttributeCombiner/AttributeCombiner.cpp:951

951                        value = val[0];
[Current thread is 1 (Thread 0x7f039ffff700 (LWP 12476))]
(gdb) list
946            for (int j = 0; j < nbAtt; j++) {
947                if (!arl[j][i].has_failed() && arl[j][i].group_element_enabled()) {
948                    vector<inType> val;
949                    arl[j][i] >> val;
950                    if (firstValue) {
951                        value = val[0];
952                        if(item->rwType == Tango::READ_WRITE){
953                            setPoint = val[1];
954                        }
955                        firstValue = false;
```

**Comment by t-b** [comment]
Something is indeed fishy.

First I've added a test for GroupAttrReply and could replicate the behaviour you are seeing that it does not throw an exception.

Then I tried with a plain attribute in https://github.com/t-b/cppTango/blob/3399515def9e6ae9bf0ccfb8e84e63dcf04ce05e/cpp_test_suite/new_tests/cxx_attr.cpp#L125 and the attribute quality is wrong on read. So this looks to be a deeper rooted problem.
