### ISSUE TITLE
log4tango: Remove LOG4TANGO_HAVE_INT64_T with std::chrono

### ISSUE THREAD

**Issue by t-b** [tango-controls/cppTango#793]
https://github.com/tango-controls/cppTango/blob/1945e6592f6d2922181bce2da235fd99f38f6b11/log4tango/src/PatternLayout.cpp#L202-L220

**Comment by mliszcz** [comment]
Hi @t-b 
I see you mentioned this issue in #759 but can't see where and if you plan to address this. Thus I did a quick PR in #794. Let's see if it passes the tests. The PR changes API and ABI of LoggingEvent but I think users are not supposed to access that directly.
