### ISSUE TITLE
get_server_info() name should be case sensitive

### ISSUE THREAD

**Issue by tango-tickets-migrator** [tango-controls/cppTango#81]
Trying to do:
import PyTango
db = PyTango.Database()
db.get_server_info('daTAbaSEds/2').name

returns:
'daTAbaSEds/2'

The method get_server_info is returning the same name that has been passed
as argument;
instead of returning the right server name from the database.

This is wrong because the server name is related to the executable name,
which is hardly case-dependant.

Reported by: tiagocoutinho

Original Ticket: [tango-cs/bugs/242](https://sourceforge.net/p/tango-cs/bugs/242)

**Comment by t-b** [comment]
Closing as stale for now. Please reopen if this is still an issue.
