### ISSUE TITLE
Post-migration cleanup

### ISSUE THREAD

**Issue by mliszcz** [tango-controls/cppTango#821]
After we move to Gitlab, we should remember about the following:
* [ ] **Fix and enable CXX::cxx_dserver_misc and event::change_event tests (if we won't do that before)**
* [ ] Enable back Sonar integration or find a local replacement
* [x] ~~Push packages to bintray on new tag (requires adding a secret in Gitlab CI/CD UI)~~
  * [ ] Push packages to gitlab package registry on new tag, remove bintray integration
* [ ] Remove coveralls integration and any supporting code (CMake module, handling in CI scripts, etc.)
* [ ] Remove travis build status and coverage badges from README (Gitlab has built-in support for showing badges in project description)
* [ ] Rename `.travis` directory to `.gitlab-ci` (or something vendor-agnostic) or remove all these scripts, but first we would need to stop requiring docker for running tests and get rid of the dind thing.
* [ ] Remove `.travis.yml`
* [ ] Mirror docker images used by CI in Gitlab container registry
* [ ] Remove github actions

**Comment by t-b** [comment]
I would vote for discontinuing bintray, we can do all we need with gitlab.
